### ISSUE TITLE
MouseComponent.Clicked remains true forever after one click?

### ISSUE THREAD

**Issue by AnkithD** [EngoEngine/engo#417] opened 2017-03-01 02:20 UTC
I have this piece of code:

func (bs *BuildingSystem) Update(dt float32) {
     for _, item := range bs.Buildings {
		if item.MouseComponent.Clicked {
			fmt.Println(item.BuildingName + " has been clicked!")
		}
	}
}

Buildings is a slice of a BuildingEntity that has a string field called BuildingName. The problem is once i click on a building, the clicked variable seems to be set to true whenever i click ANY BuildingEntity. So if i click 3 different buildings the output prints out 1,2, and 3 print statements for each of the three clicks respectively

edit: The item.MouseComponent.Clicked is actually false if nothing is clicked but is true even if it has been clicked before but not being clicked on currently

**Comment by smolderant** [comment] 2017-03-01 11:29
I see this behavior even in the "mouse" demo. Moving the cursor over the "guy" sprite changes the cursor to the hand icon, and moving it out changes it back to the normal cursor. Clicking outside of the "guy" sprite does not do anything, but clicking over the "guy" sprite gets the cursor stuck as the hand icon no matter where the cursor is moved.

I stumbled upon your issue when looking for a way to use a mouse Release action, which I haven't achieved yet. The mouse release action seemingly not being triggered may be related to how the mouse could get stuck in a "clicked" state. I added some simple print statements to demonstrate this behavior here [mouse_action_no_release_event](https://github.com/smolderant/engo/blob/mouse_action_no_release_event/demos/mouse/mouse.go#L106)

I get this output (annotated):
**mouse action press** //clicking outside "guy" area
**mouse action press** //clicking outside "guy" area (2nd time)
**mouse component entered** //entering "guy" area
**mouse component left** //leaving"guy" area
**mouse component entered** //entering "guy" area
**mouse component clicked** //clicked mouse inside "guy" area (Mouse click A)
**mouse action press** //clicked mouse inside "guy" area (Mouse click A)
//moved mouse outside "guy area" (note: no "mouse component left" output)
**mouse component clicked** //clicked mouse outside "guy" area (Mouse click B)
**mouse action press** //clicked mouse outside "guy" area (Mouse click B)

I've only tested this on Windows 7 with Go 1.7

**Comment by AnkithD** [comment] 2017-03-01 11:34
Yeah sounds about right, im facing the same problem. I also noticed that if i turn Track field to true in the mouse component clicking anyone of the entities will set ALL the entities' Clicked field to true

**Comment by countcb** [comment] 2017-03-01 13:50
I can't reproduce this on Linux. 
"Clicked" and "Released" are working as expected.

Will retry this with my windows machine once I have access to it again.

**Comment by AnkithD** [comment] 2017-03-01 17:27
Ok i've done some testing, i just have this in the Update of a system:

	if engo.Input.Mouse.Action == engo.Press {
		fmt.Println("Mouse Press")
	}
	if engo.Input.Mouse.Action == engo.Release {
		fmt.Println("Mouse Release")
	}

So when i click either the right or left mouse, i simply get a "Mouse Press" no release at all. But if rapidly click the left and right mouse buttons alternatively sometimes i get a "Mouse Release". Although, If i simply rapidly click just the left or just the right mouse button i never get a "Mouse Release"

**Comment by otraore** [comment] 2017-03-05 01:27
Closed by #423. 

Thank you for your contributions on behalf of the Engo Maintainers :D.

**Closed by otraore** 2017-03-05 01:27 UTC
